# Generated by Django 3.0.2 on 2021-03-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fruit',
            new_name='fruits',
        ),
    ]
