# Generated by Django 3.0.2 on 2021-03-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_place_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_order',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
