# Generated by Django 3.0.2 on 2021-03-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_place_order_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_order',
            name='fruits',
        ),
        migrations.AddField(
            model_name='place_order',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
