# Generated by Django 3.0.2 on 2021-03-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210310_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='place_order',
            name='fruits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Fruit'),
        ),
    ]
