# Generated by Django 3.0.2 on 2021-03-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210312_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(max_length=3, null=True),
        ),
    ]
