# Generated by Django 3.0.2 on 2021-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210312_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
