# Generated by Django 3.0.2 on 2021-03-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210316_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
