# Generated by Django 3.0.2 on 2021-03-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210317_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Fruit'),
        ),
    ]
