# Generated by Django 3.0.2 on 2021-03-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210317_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
