# Generated by Django 3.0.2 on 2021-03-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
